// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBPFIAKsCJeGtSnKbLY2UrzobynLX076A',
    appId: '1:478988131941:web:4783569ca1a5580b48b08c',
    messagingSenderId: '478988131941',
    projectId: 'bag-store-864b6',
    authDomain: 'bag-store-864b6.firebaseapp.com',
    storageBucket: 'bag-store-864b6.firebasestorage.app',
    measurementId: 'G-ZZ5KE2PMM6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9u6LBk92b_FKNJldoKE5o_FuNGiD_tZA',
    appId: '1:478988131941:android:e1292b1f7842e20048b08c',
    messagingSenderId: '478988131941',
    projectId: 'bag-store-864b6',
    storageBucket: 'bag-store-864b6.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBPFIAKsCJeGtSnKbLY2UrzobynLX076A',
    appId: '1:478988131941:web:d10207987574486c48b08c',
    messagingSenderId: '478988131941',
    projectId: 'bag-store-864b6',
    authDomain: 'bag-store-864b6.firebaseapp.com',
    storageBucket: 'bag-store-864b6.firebasestorage.app',
    measurementId: 'G-PMLTP6BBG7',
  );
}
